an:
  frontpage: 52
  main_1_0: 19
ar:
  frontpage: 100
  main_1_0: 27
be-BY:
  frontpage: 58
  main_1_0: 24
bg-BG:
  frontpage: 9
  main_1_0: 13
ca:
  frontpage: 49
  main_1_0: 18
cmn:
  frontpage: 1
  main_1_0: 8
cs:
  frontpage: 76
  main_1_0: 48
da:
  frontpage: 52
  main_1_0: 29
de:
  frontpage: 100
  main_1_0: 97
el:
  frontpage: 100
  main_1_0: 51
en-BE:
  frontpage: 0
  main_1_0: 0
en-NL:
  frontpage: 0
  main_1_0: 0
en-US: {}
eo:
  frontpage: 52
  main_1_0: 24
es:
  frontpage: 100
  main_1_0: 100
es-AR:
  frontpage: 0
  main_1_0: 0
fa-IR:
  frontpage: 60
  main_1_0: 2
fi:
  frontpage: 0
  main_1_0: 0
fr:
  frontpage: 100
  main_1_0: 98
fr-BE:
  frontpage: 0
  main_1_0: 0
ga-IE:
  frontpage: 69
  main_1_0: 61
gl:
  frontpage: 29
  main_1_0: 14
he:
  frontpage: 55
  main_1_0: 12
he-IL: {}
hi:
  frontpage: 0
  main_1_0: 0
hi-IN: {}
hr:
  frontpage: 100
  main_1_0: 6
hu:
  frontpage: 63
  main_1_0: 31
id:
  frontpage: 29
  main_1_0: 16
io:
  frontpage: 7
  main_1_0: 0
it:
  frontpage: 60
  main_1_0: 58
it-CH:
  frontpage: 0
  main_1_0: 0
it-IT: {}
ja:
  frontpage: 72
  main_1_0: 20
km:
  frontpage: 7
  main_1_0: 14
ko:
  frontpage: 100
  main_1_0: 97
ko-KR: {}
lt:
  frontpage: 23
  main_1_0: 33
lv:
  frontpage: 0
  main_1_0: 0
mi:
  frontpage: 1
  main_1_0: 3
mk:
  frontpage: 52
  main_1_0: 13
ml:
  frontpage: 9
  main_1_0: 14
ml-IN:
  frontpage: 0
  main_1_0: 0
nl: {}
nl-NL:
  frontpage: 100
  main_1_0: 31
pl:
  frontpage: 100
  main_1_0: 56
pt-BR:
  frontpage: 100
  main_1_0: 100
pt-PT:
  frontpage: 16
  main_1_0: 0
ro:
  frontpage: 100
  main_1_0: 48
ru:
  frontpage: 60
  main_1_0: 24
ru-RU: {}
sk:
  frontpage: 52
  main_1_0: 19
sl:
  frontpage: 58
  main_1_0: 26
sr:
  frontpage: 100
  main_1_0: 91
sr-RS:
  frontpage: 69
  main_1_0: 25
sv:
  frontpage: 52
  main_1_0: 19
te:
  frontpage: 15
  main_1_0: 9
te-IN: {}
th: {}
th-TH:
  frontpage: 0
  main_1_0: 0
tr:
  frontpage: 58
  main_1_0: 25
uk:
  frontpage: 72
  main_1_0: 86
ur:
  frontpage: 0
  main_1_0: 0
ur-PK:
  frontpage: 0
  main_1_0: 0
vi:
  frontpage: 7
  main_1_0: 13
zh-TW:
  frontpage: 100
  main_1_0: 100
