an:
  frontpage: 89
  main: 97
ar:
  frontpage: 89
  main: 52
be-BY:
  frontpage: 89
  main: 97
bg-BG:
  frontpage: 15
  main: 44
ca:
  frontpage: 84
  main: 81
cmn:
  frontpage: 0
  main: 30
cs:
  frontpage: 89
  main: 82
da:
  frontpage: 89
  main: 97
de:
  frontpage: 100
  main: 100
el:
  frontpage: 100
  main: 100
eo:
  frontpage: 89
  main: 95
es:
  frontpage: 89
  main: 98
fa-IR:
  frontpage: 89
  main: 13
fi:
  frontpage: 0
  main: 6
fr:
  frontpage: 89
  main: 97
ga-IE:
  frontpage: 35
  main: 47
gl:
  frontpage: 48
  main: 74
he:
  frontpage: 89
  main: 70
hr:
  frontpage: 89
  main: 49
hu:
  frontpage: 89
  main: 97
id:
  frontpage: 48
  main: 56
it:
  frontpage: 89
  main: 98
it-CH:
  frontpage: 0
  main: 0
ja:
  frontpage: 61
  main: 67
km:
  frontpage: 0
  main: 51
ko:
  frontpage: 89
  main: 60
lv:
  frontpage: 0
  main: 0
mi:
  frontpage: 2
  main: 3
mk:
  frontpage: 89
  main: 57
ml:
  frontpage: 0
  main: 55
nl-NL:
  frontpage: 100
  main: 100
pl:
  frontpage: 89
  main: 19
pt-BR:
  frontpage: 100
  main: 100
pt-PT:
  frontpage: 28
  main: 10
ro:
  frontpage: 89
  main: 97
ru:
  frontpage: 89
  main: 66
sk:
  frontpage: 89
  main: 97
sl:
  frontpage: 100
  main: 99
sr:
  frontpage: 89
  main: 97
sr-RS:
  frontpage: 89
  main: 97
sv:
  frontpage: 89
  main: 97
te:
  frontpage: 20
  main: 28
tr:
  frontpage: 89
  main: 97
uk:
  frontpage: 89
  main: 83
ur:
  frontpage: 0
  main: 0
ur-PK:
  frontpage: 0
  main: 0
vi:
  frontpage: 0
  main: 45
zh-TW:
  frontpage: 100
  main: 100
