an:
  main: 99
  frontpage: 100
ar:
  main: 53
  frontpage: 100
be-BY:
  main: 99
  frontpage: 100
bg-BG:
  main: 44
  frontpage: 18
ca:
  main: 83
  frontpage: 81
cmn:
  main: 31
  frontpage: 0
cs:
  main: 84
  frontpage: 100
da:
  main: 99
  frontpage: 100
de:
  main: 99
  frontpage: 100
el:
  main: 99
  frontpage: 100
eo:
  main: 97
  frontpage: 100
es:
  main: 100
  frontpage: 100
fa-IR:
  main: 13
  frontpage: 100
fi:
  main: 7
  frontpage: 0
fr:
  main: 99
  frontpage: 100
ga-IE:
  main: 47
  frontpage: 37
gl:
  main: 75
  frontpage: 51
he:
  main: 71
  frontpage: 100
hr:
  main: 50
  frontpage: 100
hu:
  main: 99
  frontpage: 100
id:
  main: 57
  frontpage: 51
it:
  main: 99
  frontpage: 100
it-CH:
  main: 0
  frontpage: 0
ja:
  main: 68
  frontpage: 62
km:
  main: 52
  frontpage: 0
ko:
  main: 61
  frontpage: 97
lv:
  main: 0
  frontpage: 0
mi:
  main: 0
  frontpage: 2
mk:
  main: 58
  frontpage: 100
ml:
  main: 55
  frontpage: 0
nl-NL:
  main: 99
  frontpage: 100
pl:
  main: 19
  frontpage: 100
pt-BR:
  main: 100
  frontpage: 100
pt-PT:
  main: 10
  frontpage: 25
ro:
  main: 99
  frontpage: 100
ru:
  main: 62
  frontpage: 100
sk:
  main: 99
  frontpage: 100
sl:
  main: 92
  frontpage: 100
sr:
  main: 99
  frontpage: 100
sr-RS:
  main: 99
  frontpage: 100
sv:
  main: 99
  frontpage: 100
te:
  main: 28
  frontpage: 18
tr:
  main: 99
  frontpage: 100
uk:
  main: 84
  frontpage: 100
ur:
  main: 0
  frontpage: 0
ur-PK:
  main: 0
  frontpage: 0
vi:
  main: 46
  frontpage: 0
zh-TW:
  main: 99
  frontpage: 100
