an:
  frontpage: 89
  main: 94
ar:
  frontpage: 89
  main: 50
be-BY:
  frontpage: 100
  main: 100
bg-BG:
  frontpage: 15
  main: 42
ca:
  frontpage: 84
  main: 79
cmn:
  frontpage: 0
  main: 30
cs:
  frontpage: 89
  main: 80
da:
  frontpage: 89
  main: 94
de:
  frontpage: 100
  main: 100
el:
  frontpage: 100
  main: 100
eo:
  frontpage: 89
  main: 92
es:
  frontpage: 100
  main: 99
fa-IR:
  frontpage: 89
  main: 13
fi:
  frontpage: 0
  main: 6
fr:
  frontpage: 89
  main: 94
ga-IE:
  frontpage: 35
  main: 45
gl:
  frontpage: 48
  main: 71
he:
  frontpage: 89
  main: 68
hr:
  frontpage: 89
  main: 47
hu:
  frontpage: 89
  main: 94
id:
  frontpage: 48
  main: 55
it:
  frontpage: 89
  main: 95
it-CH:
  frontpage: 0
  main: 0
ja:
  frontpage: 61
  main: 65
km:
  frontpage: 0
  main: 51
ko:
  frontpage: 89
  main: 59
lv:
  frontpage: 0
  main: 0
mi:
  frontpage: 2
  main: 3
mk:
  frontpage: 89
  main: 56
ml:
  frontpage: 0
  main: 53
nl-NL:
  frontpage: 100
  main: 100
pl:
  frontpage: 89
  main: 17
pt-BR:
  frontpage: 100
  main: 100
pt-PT:
  frontpage: 28
  main: 9
ro:
  frontpage: 89
  main: 94
ru:
  frontpage: 89
  main: 64
sk:
  frontpage: 89
  main: 94
sl:
  frontpage: 100
  main: 96
sr:
  frontpage: 89
  main: 94
sr-RS:
  frontpage: 89
  main: 94
sv:
  frontpage: 89
  main: 94
te:
  frontpage: 20
  main: 27
tr:
  frontpage: 89
  main: 94
uk:
  frontpage: 100
  main: 80
ur:
  frontpage: 0
  main: 0
ur-PK:
  frontpage: 0
  main: 0
vi:
  frontpage: 0
  main: 45
zh-TW:
  frontpage: 100
  main: 97
