an:
  frontpage: 52
  main_1_0: 18
  server: 50
ar:
  frontpage: 100
  main_1_0: 99
  server: 91
be-BY:
  frontpage: 58
  main_1_0: 23
  server: 63
bg-BG:
  frontpage: 9
  main_1_0: 13
  server: 12
ca:
  frontpage: 49
  main_1_0: 17
  server: 34
cmn:
  frontpage: 1
  main_1_0: 8
  server: 6
cs:
  frontpage: 76
  main_1_0: 57
  server: 63
da:
  frontpage: 52
  main_1_0: 27
  server: 50
de:
  frontpage: 100
  main_1_0: 90
  server: 87
el:
  frontpage: 100
  main_1_0: 47
  server: 75
en-BE:
  frontpage: 0
  main_1_0: 0
  server: 0
en-NL:
  frontpage: 0
  main_1_0: 0
  server: 0
en-US: {}
eo:
  frontpage: 52
  main_1_0: 23
  server: 50
es:
  frontpage: 100
  main_1_0: 100
  server: 100
es-AR:
  frontpage: 0
  main_1_0: 0
  server: 0
fa-IR:
  frontpage: 60
  main_1_0: 1
  server: 3
fi:
  frontpage: 100
  main_1_0: 13
  server: 7
fr:
  frontpage: 100
  main_1_0: 91
  server: 88
fr-BE:
  frontpage: 0
  main_1_0: 0
  server: 0
ga-IE:
  frontpage: 69
  main_1_0: 57
  server: 43
gl:
  frontpage: 29
  main_1_0: 13
  server: 20
he:
  frontpage: 55
  main_1_0: 11
  server: 23
he-IL: {}
hi:
  frontpage: 0
  main_1_0: 0
  server: 0
hi-IN: {}
hr:
  frontpage: 100
  main_1_0: 6
  server: 6
hu:
  frontpage: 73
  main_1_0: 29
  server: 61
id:
  frontpage: 29
  main_1_0: 15
  server: 29
io:
  frontpage: 7
  main_1_0: 0
  server: 1
it:
  frontpage: 100
  main_1_0: 78
  server: 85
it-CH:
  frontpage: 0
  main_1_0: 0
  server: 0
it-IT: {}
ja:
  frontpage: 72
  main_1_0: 19
  server: 37
km:
  frontpage: 7
  main_1_0: 13
  server: 27
ko:
  frontpage: 100
  main_1_0: 90
  server: 49
ko-KR: {}
lt:
  frontpage: 23
  main_1_0: 31
  server: 7
lv:
  frontpage: 0
  main_1_0: 0
  server: 0
mi:
  frontpage: 1
  main_1_0: 3
  server: 1
mk:
  frontpage: 52
  main_1_0: 12
  server: 31
ml:
  frontpage: 9
  main_1_0: 14
  server: 28
ml-IN:
  frontpage: 0
  main_1_0: 0
  server: 0
nl: {}
nl-NL:
  frontpage: 100
  main_1_0: 29
  server: 60
pl:
  frontpage: 100
  main_1_0: 53
  server: 24
pt-BR:
  frontpage: 100
  main_1_0: 99
  server: 100
pt-PT:
  frontpage: 16
  main_1_0: 0
  server: 3
ro:
  frontpage: 100
  main_1_0: 45
  server: 67
ru:
  frontpage: 60
  main_1_0: 23
  server: 18
ru-RU: {}
sk:
  frontpage: 52
  main_1_0: 18
  server: 50
sl:
  frontpage: 58
  main_1_0: 24
  server: 55
sr:
  frontpage: 100
  main_1_0: 90
  server: 86
sr-RS:
  frontpage: 69
  main_1_0: 23
  server: 84
sv:
  frontpage: 52
  main_1_0: 18
  server: 50
te:
  frontpage: 15
  main_1_0: 8
  server: 12
te-IN: {}
th: {}
th-TH:
  frontpage: 0
  main_1_0: 0
  server: 0
tr:
  frontpage: 100
  main_1_0: 95
  server: 90
uk:
  frontpage: 72
  main_1_0: 81
  server: 55
ur:
  frontpage: 0
  main_1_0: 0
  server: 0
ur-PK:
  frontpage: 0
  main_1_0: 0
  server: 0
vi:
  frontpage: 7
  main_1_0: 13
  server: 17
zh-TW:
  frontpage: 100
  main_1_0: 99
  server: 92
