poll:
  - "#70C9F8"
  - "#C8E56E"
  - "#D38FE1"
  - "#999FDE"
  - "#FA8295"
  - "#97D298"
  - "#C19A93"
  - "#F68AC6"
proposal:
  agree:    "#00D177"
  abstain:  "#F6A82B"
  disagree: "#F96168"
  block:    "#CE261B"
  yes:      "#00D177" # these are legacy values for agree / disagree
  no:       "#F96168"
check_in: "#70C9F8"
