loomio_marketing_styles:
  repo:         https://github.com/loomio/loomio_marketing_styles.git
  branch:       new-landing-pages

loomio_org_plugin:
  repo:         https://github.com/loomio/loomio_org_plugin.git
  branch:       new-landing-pages

loomio_legal_plugin:
  repo:         https://github.com/loomio/loomio_legal_plugin.git
