loomio_webhooks:
  repo:         loomio/loomio_webhooks

loomio_org_plugin:
  repo:         loomio/loomio_org_plugin
  branch:       move-assets-to-plugin

loomio_tags:
  repo:         loomio/loomio_tags
  experimental: true

loomio_truncate_comment:
  repo:         loomio/loomio_truncate_comment
  experimental: true

loomio_onboarding:
  repo: loomio/loomio_onboarding
  branch: add-intro-carousel

loomio_content_preview:
  repo:         gdpelican/loomio_content_preview
  experimental: true
