proposal:
  poll_options_attributes:
    - name:     "agree"
      icon_url: "img/agree.svg"
    - name:     "disagree"
      icon_url: "img/disagree.svg"
    - name:     "abstain"
      icon_url: "img/abstain.svg"
    - name:     "block"
      icon_url: "img/block.svg"
  can_add_options: true
  graph_type: pie

engagement:
  poll_options_attributes:
    - name:     "engage"
      icon_url: "img/engage.svg"
  graph_type: check

poll:
  poll_options_attributes: []
  can_add_options: true
  can_remove_options: true
  graph_type: bar
