# make as few migrations as possible .. none?

count:
  enabled: false
  name: poll_common.count
  vote_method: buttons
  material_icon: mdi-check-circle
  poll_option_name_format: i18n
  defaults:
    chart_column: voter_percent
    chart_type: bar
    icon_type: bar
    min_score: 1
    max_score: 1
    minimum_stance_choices: 1
    maximum_stance_choices: 1
    dots_per_person: 1

proposal:
  name: poll_common_form.voting_methods.agreement
  material_icon: mdi-thumbs-up-down
  enabled: true
  vote_method: buttons
  poll_option_name_format: i18n
  defaults:
    chart_column: score_percent
    chart_type: pie
    icon_type: pie
    min_score: 1
    max_score: 1
    minimum_stance_choices: 1
    maximum_stance_choices: 1
    dots_per_person: 1

poll:
  name: poll_common_form.voting_methods.single_choice
  material_icon: mdi-poll
  enabled: true
  vote_method: single_choice
  defaults:
    chart_column: max_score_percent
    chart_type: bar
    icon_type: bar
    min_score: 1
    max_score: 1
    minimum_stance_choices: 1
    maximum_stance_choices: 1
    dots_per_person: 1

multiple_choice:
  name: poll_common_form.voting_methods.multiple_choice
  material_icon: mdi-poll
  enabled: true
  vote_method: multiple_choice
  defaults:
    chart_column: max_score_percent
    chart_type: bar
    icon_type: bar
    min_score: 1
    max_score: 1

dot_vote:
  name: poll_common_form.voting_methods.allocate
  material_icon: mdi-chart-bar-stacked
  enabled: true
  vote_method: dot_vote
  defaults:
    chart_column: max_score_percent
    chart_type: bar
    icon_type: bar
    dots_per_person: 8
  validate_presence_of:
    - dots_per_person

score:
  name: poll_common_form.voting_methods.score
  material_icon: mdi-chart-gantt
  enabled: true
  vote_method: score
  chart_column: max_score_percent
  defaults:
    chart_column: max_score_percent
    chart_type: bar
    icon_type: bar
    min_score: 1
    max_score: 5
  validate_presence_of:
    - min_score
    - max_score

ranked_choice:
  name: poll_common_form.voting_methods.rank
  material_icon: mdi-format-list-numbered
  enabled: true
  vote_method: ranked_choice
  chart_column: max_score_percent
  defaults:
    chart_column: max_score_percent
    chart_type: bar
    icon_type: bar
    minimum_stance_choices: 2
  validate_presence_of:
    - mininimum_stance_choices

meeting:
  name: poll_common_form.voting_methods.time_poll
  material_icon: mdi-calendar-question
  enabled: true
  vote_method: meeting
  prevent_anonymous: true
  poll_option_name_format: iso8601
  defaults:
    chart_column: max_score_percent
    chart_type: grid
    icon_type: grid
    min_score: 0
    max_score: 2
