single_choice:
  defaults:
    minimum_stance_choices: 1
    maximum_stance_choices: 1
    min_score: 1
    max_score: 1
    dots_per_person: 1

multiple_choice:
  defaults:
    min_score: 1
    max_score: 1

dot_vote:
  defaults:
    dots_per_person: 8
  validate_presence_of:
    - dots_per_person

score:
  defaults:
    min_score: 1
    max_score: 5
  validate_presence_of:
    - min_score
    - max_score

ranked_choice:
  defaults:
    minimum_stance_choices: 2
  validate_presence_of:
    - mininimum_stance_choices

meeting:
  defaults:
    chart_type: 'grid'
    icon_type: 'grid'
    chart_column: 
    min_score: 1
    max_score: 2
    poll_option_name_format: 'iso8601'
  prevent_anonymous: true