proposal:
  poll_options_attributes:
    - name:           "agree"
    - name:           "abstain"
    - name:           "disagree"
    - name:           "block"
  graph_type:         pie
  material_icon:      thumbs_up_down
  can_remove_options: true

engagement:
  poll_options_attributes:
    - name:           "engage"
  graph_type:         check
  material_icon:      check_circle

poll:
  poll_options_attributes: []
  graph_type:         bar
  material_icon:      equalizer
  can_add_options:    true
  can_remove_options: true
