count:
  template: false
  material_icon: mdi-check-circle
  vote_method: show_thumbs
  validate_minimum_stance_choices: true
  validate_dots_per_person: true
  has_option_icon: true
  defaults:
    poll_option_name_format: i18n
    process_title_i18n: decision_tools_card.count_title
    poll_option_names:
      - 'yes'
      - 'no'
    chart_column: voter_percent
    chart_type: bar
    icon_type: bar
    min_score: 1
    max_score: 1
    minimum_stance_choices: 1
    maximum_stance_choices: 1
    dots_per_person: 1

proposal:
  template: true
  material_icon: mdi-thumbs-up-down
  vote_method: show_thumbs
  validate_minimum_stance_choices: true
  validate_dots_per_person: true
  has_option_icon: true
  per_option_reason_prompt: true
  common_poll_options:
    - name_i18n: poll_proposal_options.agree
      icon: agree
      meaning_i18n: poll_proposal_options.agree_meaning
      prompt_i18n: poll_proposal_vote_form.agree_reason_placeholder
      color: '#70C9F8'
      default: true
    - name_i18n: poll_proposal_options.abstain
      icon: abstain
      meaning_i18n: poll_proposal_options.abstain_meaning
      prompt_i18n: poll_proposal_options.abstain_prompt
      color: "#C8E56E"
      default: true
    - name_i18n: poll_proposal_options.disagree
      icon: disagree
      meaning_i18n: poll_proposal_options.disagree_meaning
      prompt_i18n: poll_proposal_vote_form.disagree_reason_placeholder
      color: "#D38FE1"
      default: true
    - name_i18n: poll_proposal_options.block
      icon: block
      meaning_i18n: poll_proposal_options.block_meaning
      prompt_i18n: poll_proposal_vote_form.block_reason_placeholder
      color: "#999FDE"
    - name_i18n: poll_proposal_options.consent
      icon: agree
      meaning_i18n: poll_proposal_options.consent_meaning
      prompt_i18n: poll_proposal_options.consent_prompt
      color: "#70C9F8"
    - name_i18n: poll_proposal_options.objection
      icon: disagree
      meaning_i18n: poll_proposal_options.objection_meaning
      prompt_i18n: poll_proposal_options.objection_prompt
      color: "#D38FE1"
  defaults:
    poll_option_name_format: plain
    process_title_i18n: decision_tools_card.proposal_title
    process_subtitle_i18n: poll_proposal_form.tool_tip_collapsed
    process_description_i18n: poll_proposal_form.tool_tip_expanded
    chart_column: score_percent
    chart_type: pie
    icon_type: pie
    min_score: 1
    max_score: 1
    minimum_stance_choices: 1
    maximum_stance_choices: 1
    dots_per_person: 1

poll:
  template: true
  material_icon: mdi-poll
  vote_method: single_choice
  can_shuffle_options: true
  validate_minimum_stance_choices: true
  validate_dots_per_person: true
  defaults:
    poll_option_name_format: plain
    process_title_i18n: poll_common_form.voting_methods.single_choice
    process_subtitle_i18n: poll_poll_form.tool_tip_collapsed
    process_description_i18n: poll_poll_form.tool_tip_expanded
    chart_column: max_score_percent
    chart_type: bar
    icon_type: bar
    min_score: 1
    max_score: 1
    minimum_stance_choices: 1
    maximum_stance_choices: 1
    dots_per_person: 1

multiple_choice:
  template: true
  material_icon: mdi-poll
  vote_method: multiple_choice
  can_shuffle_options: true
  validate_minimum_stance_choices: true
  validate_max_score: true
  defaults:
    poll_option_name_format: plain
    process_title_i18n: poll_common_form.voting_methods.multiple_choice
    process_subtitle_i18n: poll_common_form.voting_methods.multiple_choice_hint
    process_description_i18n: poll_poll_form.tool_tip_expanded
    chart_column: max_score_percent
    chart_type: bar
    icon_type: bar
    min_score: 1
    max_score: 1
    minimum_stance_choices: 1

dot_vote:
  template: true
  material_icon: mdi-chart-bar-stacked
  vote_method: allocate
  can_shuffle_options: true
  validate_min_score: true
  validate_dots_per_person: true
  defaults:
    poll_option_name_format: plain
    process_title_i18n: decision_tools_card.dot_vote_title
    process_subtitle_i18n: poll_common_form.voting_methods.allocate_hint
    process_description_i18n: poll_dot_vote_form.tool_tip_expanded
    chart_column: max_score_percent
    chart_type: bar
    icon_type: bar
    dots_per_person: 8
    min_score: 0
    minimum_stance_choices: 0

score:
  template: true
  material_icon: mdi-chart-gantt
  vote_method: score
  can_shuffle_options: true
  validate_min_score: true
  validate_max_score: true
  defaults:
    poll_option_name_format: plain
    process_title_i18n: decision_tools_card.score_title
    process_subtitle_i18n: poll_common_form.voting_methods.score_hint
    process_description_i18n: poll_score_form.tool_tip_expanded
    chart_column: max_score_percent
    chart_type: bar
    icon_type: bar
    min_score: 1
    max_score: 5
    minimum_stance_choices: 1

ranked_choice:
  template: true
  material_icon: mdi-format-list-numbered
  vote_method: ranked_choice
  can_shuffle_options: true
  validate_minimum_stance_choices: true
  require_all_choices: true
  validate_min_score: true
  defaults:
    poll_option_name_format: plain
    process_title_i18n: decision_tools_card.ranked_choice_title
    process_subtitle_i18n: poll_common_form.voting_methods.ranked_choice_hint
    process_description_18n: poll_ranked_choice_form.tool_tip_expanded
    chart_column: max_score_percent
    chart_type: bar
    icon_type: bar
    minimum_stance_choices: 2
    min_score: 1

meeting:
  template: true
  material_icon: mdi-calendar-question
  prevent_anonymous: true
  vote_method: time_poll
  require_all_choices: true
  validate_min_score: true
  validate_max_score: true
  defaults:
    meeting_duration: 60
    poll_option_name_format: iso8601
    process_title_i18n: decision_tools_card.meeting_title
    process_subtitle_i18n: poll_common_form.voting_methods.time_poll_hint
    process_description_i18n: poll_meeting_form.tool_tip_expanded
    chart_column: max_score_percent
    chart_type: grid
    icon_type: grid
    min_score: 0
    max_score: 2
