count:
  enabled: false
  material_icon: mdi-check-circle
  poll_option_name_format: i18n
  vote_method: show_thumbs
  defaults:
    chart_column: voter_percent
    chart_type: bar
    icon_type: bar
    min_score: 1
    max_score: 1
    minimum_stance_choices: 1
    maximum_stance_choices: 1
    dots_per_person: 1

proposal:
  enabled: true
  material_icon: mdi-thumbs-up-down
  poll_option_name_format: i18n
  vote_method: show_thumbs
  i18n_defaults:
    process_name: decision_tools_card.proposal_title
  defaults:
    poll_option_names:
      - agree
      - abstain
      - disagree
    chart_column: score_percent
    chart_type: pie
    icon_type: pie
    min_score: 1
    max_score: 1
    minimum_stance_choices: 1
    maximum_stance_choices: 1
    dots_per_person: 1

poll:
  enabled: true
  material_icon: mdi-poll
  poll_option_name_format: 'none'
  vote_method: single_choice
  can_shuffle_options: true
  defaults:
    chart_column: max_score_percent
    chart_type: bar
    icon_type: bar
    min_score: 1
    max_score: 1
    minimum_stance_choices: 1
    maximum_stance_choices: 1
    dots_per_person: 1

multiple_choice:
  enabled: true
  material_icon: mdi-poll
  poll_option_name_format: none
  vote_method: multiple_choice
  can_shuffle_options: true
  defaults:
    chart_column: max_score_percent
    chart_type: bar
    icon_type: bar
    min_score: 1
    max_score: 1

dot_vote:
  enabled: true
  material_icon: mdi-chart-bar-stacked
  poll_option_name_format: none
  vote_method: allocate
  can_shuffle_options: true
  defaults:
    chart_column: max_score_percent
    chart_type: bar
    icon_type: bar
    dots_per_person: 8
  validate_presence_of:
    - dots_per_person

score:
  enabled: true
  material_icon: mdi-chart-gantt
  poll_option_name_format: none
  vote_method: score
  can_shuffle_options: true
  defaults:
    chart_column: max_score_percent
    chart_type: bar
    icon_type: bar
    min_score: 1
    max_score: 5
  validate_presence_of:
    - min_score
    - max_score

ranked_choice:
  enabled: true
  material_icon: mdi-format-list-numbered
  poll_option_name_format: none
  vote_method: ranked_choice
  can_shuffle_options: true
  defaults:
    chart_column: max_score_percent
    chart_type: bar
    icon_type: bar
    minimum_stance_choices: 2
  validate_presence_of:
    - mininimum_stance_choices

meeting:
  enabled: true
  material_icon: mdi-calendar-question
  poll_option_name_format: iso8601
  prevent_anonymous: true
  vote_method: time_poll
  defaults:
    chart_column: max_score_percent
    chart_type: grid
    icon_type: grid
    min_score: 0
    max_score: 2
