---
development:
 :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 4 %>
production:
 :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 4 %>
:queues:
  - critical
  - mailers
  - default
  - low
  - low_priority
